name: Build and Publish Binaries

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
        - name: linux
          os: ubuntu-latest
          artifact_name: target/release/clique-collector
          asset_name: clique-collector-linux
        - name: windows
          os: windows-latest
          artifact_name: target/release/clique-collector.exe
          asset_name: clique-collector-windows
        - name: macos
          os: macos-latest
          artifact_name: target/release/clique-collector
          asset_name: clique-collector-macos

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Set up rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}

  publish:
    name: Publish artifacts as release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: ./artifacts
      run: |
        chmod +x ./artifacts/clique-collector-linux/clique-collector
        chmod +x ./artifacts/clique-collector-macos/clique-collector
      # No point making the exe file executable since Windows doesn't care.

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: Upload Linux artifacts to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/clique-collector-linux/clique-collector
        asset_name: clique-collector-linux
        asset_content_type: application/x-elf

    - name: Upload MacOS artifacts to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/clique-collector-macos/clique-collector
        asset_name: clique-collector-macos
        asset_content_type: application/x-mach-o

    - name: Upload Windows artifacts to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/clique-collector-windows/clique-collector.exe
        asset_name: clique-collector.exe
        asset_content_type: application/x-msdownload
